### ISSUE TITLE
Broken by stream-combiner2@1.1.0?

### ISSUE THREAD

**Issue by rclark** [substack/osm-pbf-parser#15]
Some of my tests for a module that depends on osm-pbf-parser started failing ~2hr ago when https://github.com/substack/stream-combiner2/commit/852cd7954631d24fc3937f94afd3495f37a60c99 landed in NPM. 

```
TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at PrimitivesParser.<anonymous> (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/stream-combiner2/node_modules/duplexer2/index.js:54:10)
    at PrimitivesParser.emit (events.js:92:17)
    at emitReadable_ (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/readable-stream/lib/_stream_readable.js:456:10)
    at emitReadable (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/readable-stream/lib/_stream_readable.js:450:7)
    at readableAddChunk (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/readable-stream/lib/_stream_readable.js:206:11)
    at PrimitivesParser.Readable.push (/home/travis/build/.../node_modules/osm-pbf-parser/node_modules/readable-stream/lib/_stream_readable.js:162:10)
```

I couldn't exactly confirm the failure in this repo, because the tests depend on an extract that isn't included (I think?). However pinning stream-combiner2@1.0.2 allowed my module's tests to pass.

**Comment by substack** [comment]
Try now (stream-combiner2@1.1.1): I updated the duplexer() call to forward the options, which should turn objectMode on.

**Comment by rclark** [comment]
Hmm now it seems like the `end` event isn't getting fired. Also figured out how `test/extracts/fetch.sh` worked and osm-pbf-parser tests fail on stream-combiner@1.1.1

**Comment by substack** [comment]
pegged to the old version for now, but it would be good to fix this upstream if possible

**Comment by shinnn** [comment]
> it would be good to fix this upstream if possible

Fixed in duplexer2. https://github.com/deoxxa/duplexer2/commit/44cef46047f272b9095595187d57b103380c2b39

Now this project passes the test with stream-combiner@1.1.1.

**Comment by substack** [comment]
unpegged in the 2.2.0 release along with some other minor dependency upgrades
